import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React from "react";
import Link from "next/link";

const inter = Inter({ subsets: ['latin'] })

interface tHomeProps {
    posts: number[]
}

export default function Home(props: tHomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <div>
              <h3>List of Hacker News Post IDs</h3>
              {props.posts.length > 0 && props.posts.map((postId: number) => (
                  <div key={postId}>
                      <Link href={`/${postId}`}>
                          <span>{postId}</span>
                      </Link>
                  </div>
              ))}
          </div>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>



          <Link href={'/about'}>
              Get started
              {/*<a>About</a>*/}
          </Link>
        </div>
      </main>
    </>
  )
}

export const getStaticProps = async (context: any) => {
    try {
        const res = await fetch('https://hacker-news.firebaseio.com/v0/topstories.json?print=pretty');
        const postIds: number[] = await res.json();
        return {
            props: {
                posts: postIds
            }
        };
    }
    catch (e) {
        console.log(e);
    }
}